extraEnvs:
  - name: ELASTIC_USERNAME
    valueFrom:
      secretKeyRef:
        name: elasticsearch-master-credentials
        key: username
  - name: ELASTIC_PASSWORD
    valueFrom:
      secretKeyRef:
        name: elasticsearch-master-credentials
        key: password

logstashPipeline:
  logstash.conf: |
    input {
      http {
        port => 8080
      }
    }
    output {
      elasticsearch {
        hosts => ["https://elasticsearch-master.elastic.svc:9200"]
        user => "${ELASTIC_USERNAME}"
        password => "${ELASTIC_PASSWORD}"
        ssl => true
        cacert => "/usr/share/logstash/config/certs/ca.crt"

        index => "logstash-%{+YYYY.MM.dd}"
      }
    }
logstashConfig:
  logstash.yml: |
    http.host: "0.0.0.0"
    http.port: 9600

    xpack.monitoring.enabled: true
    xpack.monitoring.elasticsearch.hosts:
      - https://elasticsearch-master.elastic.svc:9200
    xpack.monitoring.elasticsearch.username: ${ELASTIC_USERNAME}
    xpack.monitoring.elasticsearch.password: ${ELASTIC_PASSWORD}
    xpack.monitoring.elasticsearch.ssl.certificate_authority: /usr/share/logstash/config/certs/ca.crt

extraVolumes:
  - name: elasticsearch-certs
    secret:
      secretName: elasticsearch-master-certs

extraVolumeMounts:
  - name: elasticsearch-certs
    mountPath: /usr/share/logstash/config/certs
    readOnly: true

service:
  annotations: {}
  type: ClusterIP
  ports:
  #   - name: beats
  #     port: 5044
  #     protocol: TCP
  #     targetPort: 5044
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
